added basic code structure
EMXzzz/vk-clone pull request #1
Opened 2022-03-04 06:29 UTC by EMXzzz

2022-03-04 06:44 UTC, Neumann88 requested changes

2022-03-04 06:44 UTC, Neumann88 commented on src/components/layout/header/header.tsx
>  export const Header = () => {
layout - это абстрактный слой , который чаще служит просто прослойков для соединения или изменения компонентов, header, sidebar - это полноценные компоненты, скорее это widgets

2022-03-04 06:44 UTC, Neumann88 commented on src/components/layout/header/header.tsx
> +        <div></div>
если ты создаешь папку для компонента как пример header/header.tsx , то лучше создать индексовый файл index.ts куда ты будешь экспортить твой компонент 
пример

export {Header} from './header.tsx';

тогда при импорте этого компонента/функции/переменных итд - тебе не нужно будет указвать путь напрямую до файла  то есть будет выглядить так import {Header} from './header', иначе у тебя будет так import {Header} from './header/header.tsx' (.tsx для наглядности написал, так в тс не указывается расширение)

2022-03-04 06:44 UTC, Neumann88 commented on src/components/routes/routes.tsx
компонент роутс - что из себя должен представлять? если его задача объявить роутинг то это делается как раз в лейауте, пример

сразу скажу, такие вещи как урлы, повторяющиеся значения (строки, числа) выводи в константы
и лучше создать как раз таки папку helper где будет файл с название constatns.ts в котором будут лежать эти константы

это для урлов роутинга - правило наименования таких констант только заглавные буквы и разделение слов через нижние подчеркивание, пример: HOME, SIGN_IN, INSURED_EVENTS итд

для повторяющихся строк,чисел - по месту использования 

к примеру у тебя директории insured-page -> components -> insured-user, insured-customer (на нейминг не зацикливайся написал от пизды) и в insured-user, insured-customer - есть повторяющиеся какие то значения, то вынести эти повторяющиеся значения нужно в helpers в insured-page

<Swich>
   <Route exact to={...}>
          <Header />
    </Route>
</Swich>

2022-03-04 07:35 UTC, Neumann88 commented on src/components/layout/header/header.tsx
>  export const Header = () => {
видимо ты не так понял меня, дирректория widgets - header, sidebar  это виджеты отдельные

2022-03-04 09:21 UTC, EMXzzz commented on src/components/layout/header/header.tsx
> +        <div></div>
+

2022-03-04 09:21 UTC, EMXzzz commented on src/components/layout/header/header.tsx
>  export const Header = () => {
+

2022-03-04 09:39 UTC, EMXzzz commented on src/components/layout/header/header.tsx
> +        <div></div>
+

2022-03-05 00:19 UTC, Neumann88 requested changes

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layers/routes/routes.tsx
> +            {routes.map(route => {
маппой проходиться конечно можно, но это лишнее, может быть такой кейс что для каждой страницы тебе нужно конфигурировать свой роут и защиту по свойму, поэтому я бы убрал мап

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layers/routes/routes.tsx
> +                    <Widgets children={undefined} />
children - это пропс, но отличие то что это ребенок обернутым твоим компонентом
пример:

<Layout>
    <Header/>
</Layout>

Header - является в данном случает children 

так же не обязательно это может быть только один компонент или jsx 

<Layout>
    <Header/>
    <Sidebar/>
</Layout>

в данном примере хедер и сайдбар - это один чилдрен пропс у лейаута

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layout/index.ts
> +export {Widgets} from '../layout/widgets'
переименуй на Layout

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layout/widgets.tsx
> +        <div>
замени на див на React.Fragment - почитай что и как пишется в скоращенной форме

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layout/widgets.tsx
> +            <Grid container spacing={2} marginX={5} marginTop={3}>
более одного переданного атрибута, сделай выравнивание

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layout/widgets.tsx
> +                <Grid item md={10}>
тоже самое более одного аттрибута и у грида выше тоже самое

2022-03-05 00:19 UTC, Neumann88 commented on src/components/pages/home/home.tsx
>          <div>
React.Fragment

2022-03-05 00:19 UTC, Neumann88 commented on src/components/widgets/sidebar/sidebar.tsx
>          <div>
React.Fragment - если у тебя что то будет еще , если нет то избавляйся от UserItems и помести содержимое в сайдбар - если это конечно же отвечает за навигацию

2022-03-05 00:19 UTC, Neumann88 commented on src/components/layers/routes/routes.tsx
> +    BrowserRouter as Router,
все провайдеры - должны подключаться в index.ts, BrowserRouter - это провайдер для роутинга

2022-03-07 11:32 UTC, Neumann88 approved these changes

2022-03-07 11:32 UTC, merged