ф
EMXzzz/vk-clone pull request #2
Opened 2022-03-09 04:22 UTC by EMXzzz

2022-03-09 04:54 UTC, Neumann88 requested changes

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +import {ChangeEvent, KeyboardEvent, useState} from "react";
Выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/layers/content/content.tsx
> +    Conversation,
1 компонент 1 ответственность

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/auth/auth.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/friends/friends.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +import { users } from "../../widgets/sidebar/user-items";
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +export const AddPost = ({setPosts}: AddPost) => {
нейминг

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +    const [content, setContent] = useState<string>('')
что за контент? нейминг

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +        {setPosts(prev => [
что за выравнивание ебнутое

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/add-post.tsx
> +        setContent('')
таб

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/home.tsx
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/home.tsx
> +import {useState} from "react";
реакт первый потом материал

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/initial-post.tsx
> +export const initialPost: Post[] = [
если это мок то не нужно отдельного файла, используй эту константу по месту присвоения

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/home.tsx
> +    const [posts, setPosts] = useState<Post[]>(initialPost)
вообще у всех пользователей будет initialPost один и тот же? зачем это , если это мок то добавь TO-DO

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/initial-post.tsx
> +import { Post } from "../../types/post";
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +import { Post } from "../../types/post";
выравнивание + отступ сделай

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +            {posts.map((post, index) =>
return posts.map()

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                        to={`profile_id${post.author._id}`}
у тебя во первых есть константа с урлом PROFILE_ID, во вторых у тебя линка будет переходить на localhost:8080profile_id321123

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                        style={{
css используй, инлайн стили писать плохая практика

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                            <div style={{fontSize: 14}}>{post.author.name}</div>
css, пройдись по проекту и везде где у тебя стили инлайн - убери и сделай по нормальному

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                    {post?.images?.length &&(
если у тебя post.images.length будет 0 то && возвращает первое ложно, 0 это ложно поэтому у тебя на страницы будет отображаться 0, корректно сделать проверку 0 < post.images.length && .... тогда будет false и на странице ничего не будет

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                    {post?.images?.length &&(
{ 0 > post.images.length && <ImageList variant="masonry" cols={3} gap={8}) }
{ post.images.map(...) }

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                        <ImageList variant="masonry" cols={3} gap={8}>
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                                    alt={''}
в {} ты запихиваешь какие то сущности созданные тобой, строки ты можешь просто пропихивать как строки не нужно их в {} оборачивать

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/home/posts.tsx
> +                                    alt={''}
вообще выглядит так что этот атрибут можно и не добавлять а убрать

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/messages/conversation.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/messages/messages.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/pages/profile/profile.tsx
> +
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/types/post.ts
> +import { Dispatch, SetStateAction } from "react"
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/types/post.ts
> +export interface Post {
User и Post не выглядят как глобальные интерфейсы, они должны быть объявлены и лежать по месту их назначения

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +import { useState } from "react";
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +    const [isSearchActive, setIsSearchActive] = useState(false)
нет типизации

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +                <img src={logoImg} alt="logo" />
2 и более атрибута - выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on package.json
>      "@types/react-dom": "^17.0.13",
ты добавил css модули, если все работает, судя по хедеру работает. то во всем проекте замени на css модули

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +                {!isSearchActive &&
{!isSearchActive && <Search/>}

название сущности говорит о том что поиск активный значит когда она тру у тебя поиск должен быть, либо не корректное название сущности либо не правильная логика

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +                        setIsSearchActive(true)
использование колбеков внутри эевентов - плохая практика, создай хендлер

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/menu/friends.tsx
> +import {useHistory} from "react-router-dom";
все картинки должны лежать за пределами src

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/sidebar.tsx
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
лишний отступ

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +            <Link
выравнивание (таб)

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                to={`profile_id${user._id}`}
уже написал об этом

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                        position: "relative",
про стили тоже написал

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                        border: '2px solid #F1F7FA',
выравнивание

2022-03-09 04:54 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +export const users = [
затипизируй константу тогда можно использовать деструктуризацию при маппинге

2022-03-10 03:11 UTC, EMXzzz commented on src/pages/home/add-post.tsx
> +import {ChangeEvent, KeyboardEvent, useState} from "react";
> Выравнивание

+

2022-03-10 03:11 UTC, EMXzzz commented on src/layers/content/content.tsx
> +    Conversation,
> 1 компонент 1 ответственность

+

2022-03-10 03:11 UTC, EMXzzz commented on src/pages/auth/auth.tsx
> +
+

2022-03-10 03:11 UTC, EMXzzz commented on src/pages/friends/friends.tsx
> +
+

2022-03-10 03:11 UTC, EMXzzz commented on src/pages/home/add-post.tsx
> +import { users } from "../../widgets/sidebar/user-items";
+

2022-03-10 03:11 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +            <Link
> выравнивание (таб)

+

2022-03-10 03:11 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                to={`profile_id${user._id}`}
+

2022-03-10 03:11 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                        position: "relative",
+

2022-03-10 03:11 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                        border: '2px solid #F1F7FA',
+

2022-03-10 03:11 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +export const users = [
+

2022-03-10 03:34 UTC, Neumann88 requested changes

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/add-post/add-post.module.css
> +.add-post {
нейминг - post-creator

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/auth/sign-up/sign-up.tsx
> +        <Grid
лишнее

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/auth/sign-up/sign-up.module.css
> +    display: block;
flex, остальные стили не будут работать т.к они работают только с flex

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/auth/sign-in/sign-in.tsx
> +        <Grid
лишнее

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/add-post/add-post.tsx
> +            const post = {
допиши TODO  что это заглушка временная

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/add-post/add-post.tsx
> +        <Box className={classes['add-post']} >
это контейнер, поэтому лучше задать класс post-creator-container

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/add-post/add-post.tsx
> +                className={classes['input-post']}
это уже непосредственно сам creator поэтому post-creator

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/add-post/index.ts
> +export {AddPost} from './add-post'
нейминг

2022-03-10 03:34 UTC, Neumann88 commented on src/pages/feed/components/posts/posts.tsx
> +                    {(post.images && 0 < post?.images?.length) && (
вынеси это в константу и дай соотвествующий нейминг

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/header/header.tsx
> +import {ChangeEvent, useState} from "react";
выравнивание

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/components/menu/friends.tsx
> +    }
отступ в 1 строку между 19 и 20 строкой

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/components/menu/news.tsx
> +    }
отступ

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/components/menu/profile.tsx
> +    }
отступ

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                    to={`profile_id${user._id}`}
используй константу PROFILE

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                    className={classes['user-id']}
не корректный нейминг у класса

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                    <Box className={classes['user-box']}>
не корректный нейминг у класса

2022-03-10 03:34 UTC, Neumann88 commented on src/widgets/sidebar/user-items.tsx
> +                        {user.isInNetwork && <Box className={classes['user-is-in-network']}/>}
не понятно что это и зачем нужно

2022-03-10 03:55 UTC, Neumann88 requested changes

2022-03-10 03:55 UTC, Neumann88 commented on src/pages/feed/components/post-creator/post-creator.tsx
> +    const handleAddPost = (event: KeyboardEvent<HTMLInputElement>) => { //TODO заглушка
да напротив объекта епт, функция то у тебя не заглушка

2022-03-10 03:55 UTC, Neumann88 commented on src/pages/feed/components/post-creator/post-creator.tsx
> +                className={classes['input-post']}
текст филд это post-creator
box - это контейнер post-creator-container

2022-03-10 03:55 UTC, Neumann88 commented on src/pages/feed/components/posts/posts.tsx
> +                        <Box className={classes['post-box']}>
нейминг опять

2022-03-10 03:55 UTC, Neumann88 commented on src/types/png.d.ts
> +    const value: import('react-native').ImageSourcePropType;
какой к хуям реакт нейтив

2022-03-10 04:11 UTC, EMXzzz commented on src/types/png.d.ts
> +    const value: import('react-native').ImageSourcePropType;
+

2022-03-10 04:11 UTC, EMXzzz commented on src/pages/feed/components/posts/posts.tsx
> +                        <Box className={classes['post-box']}>
+

2022-03-10 04:11 UTC, EMXzzz commented on src/pages/feed/components/post-creator/post-creator.tsx
> +                className={classes['input-post']}
+

2022-03-10 04:11 UTC, EMXzzz commented on src/pages/feed/components/post-creator/post-creator.tsx
> +    const handleAddPost = (event: KeyboardEvent<HTMLInputElement>) => { //TODO заглушка
+

2022-03-10 04:12 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                    <Box className={classes['user-box']}>
+

2022-03-10 04:12 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                    className={classes['user-id']}
+

2022-03-10 04:12 UTC, EMXzzz commented on src/widgets/sidebar/user-items.tsx
> +                    to={`profile_id${user._id}`}
+

2022-03-10 04:12 UTC, EMXzzz commented on src/widgets/sidebar/components/menu/profile.tsx
> +    }
+

2022-03-10 04:12 UTC, EMXzzz commented on src/pages/feed/components/add-post/add-post.tsx
> +            const post = {
+

2022-03-10 04:12 UTC, EMXzzz commented on src/pages/auth/sign-in/sign-in.tsx
> +        <Grid
+

2022-03-10 04:12 UTC, EMXzzz commented on src/pages/auth/sign-up/sign-up.module.css
> +    display: block;
+

2022-03-10 04:12 UTC, EMXzzz commented on src/pages/auth/sign-up/sign-up.tsx
> +        <Grid
+

2022-03-10 04:12 UTC, EMXzzz commented on src/pages/feed/components/add-post/add-post.module.css
> +.add-post {
+

2022-03-10 05:08 UTC, Neumann88 approved these changes

2022-03-10 05:35 UTC, merged